# Generated by Django 4.2.15 on 2025-11-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoveryapi', '0002_program_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='content_type',
            field=models.CharField(help_text="Machine-friendly key (e.g. 'hero_headline', 'contact_phone').", max_length=100, unique=True),
        ),
    ]
