# Generated by Django 4.2.15 on 2025-11-08 15:36

from django.db import migrations, models
import django.db.models.deletion


def create_program_types(apps, schema_editor):
    Program = apps.get_model('recoveryapi', 'Program')
    ProgramType = apps.get_model('recoveryapi', 'ProgramType')

    default_types = {
        'PHP': 'Partial Hospitalization Program',
        'IOP': 'Intensive Outpatient Program',
        'VOC': 'Vocational Rehabilitation',
        'RES': 'Respite Housing',
    }

    # Seed default program types
    for code, name in default_types.items():
        ProgramType.objects.get_or_create(code=code, defaults={'name': name})

    # Map existing programs to seeded types
    for program in Program.objects.all():
        code = getattr(program, 'program_type', None)
        if not code:
            continue
        try:
            program_type = ProgramType.objects.get(code=code)
        except ProgramType.DoesNotExist:
            program_type = ProgramType.objects.create(code=code, name=code)
        program.program_type_rel = program_type
        program.save(update_fields=['program_type_rel'])


class Migration(migrations.Migration):

    dependencies = [
        ('recoveryapi', '0003_alter_sitecontent_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="Short identifier used by the frontend (e.g. 'IOP').", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-friendly name.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='program',
            name='program_type_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='recoveryapi.programtype'),
        ),
        migrations.RunPython(create_program_types, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='program',
            name='program_type',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='program_type_rel',
            new_name='program_type',
        ),
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='recoveryapi.programtype'),
        ),
    ]
